pipeline {
    agent any

    stages {

        stage('Login DockerHub'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'Dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                sh 'docker login -u $USERNAME -p $PASSWORD'
                }
                }
        }

        stage('Pull image'){
            steps{
                sh 'docker pull papagoose/catvsdog:latest'
            }
        }

        stage('Run container'){
            steps{
                sh 'docker run --name catvsdog -p 80:5556 -d papagoose/catvsdog:latest'
            }
        }
        stage('Checkout container logs') {
            steps {
                dir("catsvsdogs") {
                        sh 'docker logs --tail 1000 catvsdog'
                    }
            }
        }
	}

    post {
        always {
            sh 'docker stop catvsdog && docker logout'
        }
    }
}