pipeline {
    agent any
    stages {
        stage('Login DockerHub'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'Dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                sh 'docker login -u $USERNAME -p $PASSWORD'
                }
                }
        }

        stage('Pull image'){
            steps{
                sh 'docker pull papagoose/catvsdog:latest'
            }
        }
        stage('Run container'){
            steps{
                sh 'docker run --name catsvsdogs -p 80:5556 -d papagoose/catvsdog:latest'
            }
        }
	}

    post {
        always {
            sh 'docker stop catsvsdogs && docker logout'
        }
    }
}