pipeline {
    agent any
    stages {
        stage('Up container'){
            steps{
                sh 'cd .. && cd CI/catsvsdogs && /usr/bin/docker-compose up -d --remove-orphans'
                sleep(time:60, unit: 'SECONDS')
            }
        }

        stage('Checkout container logs') {
            steps {
                    sh 'cd .. && cd CI/catsvsdogs && /usr/bin/docker-compose logs -t --tail 100'
            }
        }
	}

    post {
        always {
            sh 'docker stop catsvsdogs_web_1 && docker logout'
        }
    }
}