pipeline {
    agent any
    stages {
        stage('Git clone'){
            steps {
                script {
                    try {
                        sh 'git clone -b dev https://github.com/PapaGoose/catsvsdogs.git'
                    }
                    catch (exc) {
                        echo 'catsvsdog already cloned'
                    }
                
                }
            }
        
        }
        stage('Pull from repo') {
            steps {
                sh '''
                    cd catsvsdogs
                    git pull origin dev'''
            }
        }
        stage('Checkout dir'){
            steps{
                sh 'cd catsvsdogs && ls'
            }
        }
        stage('Build docker image'){
            steps{
                sh '''
                    chmod -R 777 ./catsvsdogs && cd catsvsdogs && pwd && docker-compose build
                '''
            }
        }
    }
}