pipeline {
    agent any
    stages {
        stage('Login DockerHub'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'Dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                sh 'docker login -u $USERNAME -p $PASSWORD'
                }
                }
        }
        stage('Git clone'){
            steps {
                cleanWs()
                sh 'git clone -b dev https://github.com/PapaGoose/catsvsdogs.git'
                }
        }
        stage('Checkout dir'){
            steps{
                sh 'cd catsvsdogs && ls'
            }
        }
        stage('Build docker image'){
            steps{
                    sh 'cd catsvsdogs && /usr/bin/docker-compose build'
                }
        }
        stage('Push image to registry'){
            steps{
                sh 'docker push papagoose/catvsdog:latest'
            }
        }
    }
}