pipeline {
    agent any
    environment {
        DOCKERHUB_CREDS=credentials('Dockerhub')
    }
    stages {
        stage('Login DockerHub'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'Dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                sh 'docker login -u $USERNAME -p $PASSWORD'
                }
                }
        }
        stage('Git clone'){
            steps {
                cleanWs()
                sh 'git clone -b dev https://github.com/PapaGoose/catsvsdogs.git'
                }
        }
        stage('Checkout dir'){
            steps{
                sh 'cd catsvsdogs && ls'
            }
        }
        stage('Build docker image'){
            steps{
                script{
                    try{
                        sh 'cd catsvsdogs && /usr/bin/docker-compose build'
                    }
                    finally{
                        sh 'cd catsvsdogs && /usr/bin/docker-compose up -d --remove-orphans'
                    }
                }

            }
        }
        stage('Push image to registry'){
            steps{
                sh 'docker push papagoose/catvsdog:latest'
            }
        }
    }
}